version: 2
updates:
  - package-ecosystem: maven
    directories:
      - "spring-boot-client"
      - "spring-boot-server"
    schedule:
      interval: daily
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "spring-boot-server"
      - "spring-boot-client"
    schedule:
      interval: daily